title: Homepage
logo: /assets/img/logo.png
description: My CS and ME Projects
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
repository: krys10nel/krys10nel.github.io
domain: krys10nel.github.io
url: https://krys10nel.github.io
baseurl: /krys10nel.github.io/